CREATE INDEX idx_chord_complexity ON public.musical_metadata USING btree (chord_complexity_score) WHERE (chord_complexity_score IS NOT NULL);
CREATE INDEX idx_chord_progression ON public.musical_metadata USING gin (chord_progression);
CREATE INDEX idx_chord_types ON public.musical_metadata USING gin (chord_types);
CREATE INDEX idx_files_batch ON public.files USING btree (import_batch_id) WHERE (import_batch_id IS NOT NULL);
CREATE INDEX idx_files_collection ON public.files USING btree (collection_name) WHERE (collection_name IS NOT NULL);
CREATE INDEX idx_files_copyright ON public.files USING btree (copyright) WHERE (copyright IS NOT NULL);
CREATE INDEX idx_files_copyright_trgm ON public.files USING gin (copyright public.gin_trgm_ops) WHERE (copyright IS NOT NULL);
CREATE INDEX idx_files_created ON public.files USING btree (created_at DESC);
CREATE INDEX idx_files_display_name ON public.files USING btree (display_name);
CREATE INDEX idx_files_duration ON public.files USING btree (duration_seconds) WHERE (duration_seconds IS NOT NULL);
CREATE INDEX idx_files_filename_bpm ON public.files USING btree (filename_bpm) WHERE (filename_bpm IS NOT NULL);
CREATE INDEX idx_files_filename_bpm_key ON public.files USING btree (filename_bpm, filename_key) WHERE ((filename_bpm IS NOT NULL) OR (filename_key IS NOT NULL));
CREATE INDEX idx_files_filename_genres ON public.files USING gin (filename_genres) WHERE ((filename_genres IS NOT NULL) AND (array_length(filename_genres, 1) > 0));
CREATE INDEX idx_files_filename_key ON public.files USING btree (filename_key) WHERE (filename_key IS NOT NULL);
CREATE INDEX idx_files_filepath ON public.files USING btree (filepath);
CREATE INDEX idx_files_folder_tags ON public.files USING gin (folder_tags);
CREATE INDEX idx_files_format ON public.files USING btree (format);
CREATE INDEX idx_files_instrument_names_text ON public.files USING gin (instrument_names_text) WHERE ((instrument_names_text IS NOT NULL) AND (array_length(instrument_names_text, 1) > 0));
CREATE INDEX idx_files_manufacturer ON public.files USING btree (manufacturer) WHERE (manufacturer IS NOT NULL);
CREATE INDEX idx_files_markers ON public.files USING gin (markers) WHERE ((markers IS NOT NULL) AND (array_length(markers, 1) > 0));
CREATE INDEX idx_files_metadata_source ON public.files USING btree (metadata_source);
CREATE INDEX idx_files_num_tracks ON public.files USING btree (num_tracks);
CREATE INDEX idx_files_parent ON public.files USING btree (parent_file_id) WHERE (parent_file_id IS NOT NULL);
CREATE INDEX idx_files_parent_folder ON public.files USING btree (parent_folder) WHERE (parent_folder IS NOT NULL);
CREATE INDEX idx_files_search ON public.files USING gin (search_vector);
CREATE INDEX idx_files_structure_tags ON public.files USING gin (structure_tags) WHERE ((structure_tags IS NOT NULL) AND (array_length(structure_tags, 1) > 0));
CREATE INDEX idx_files_track_names ON public.files USING gin (track_names) WHERE ((track_names IS NOT NULL) AND (array_length(track_names, 1) > 0));
CREATE INDEX idx_files_track_number ON public.files USING btree (track_number) WHERE (track_number IS NOT NULL);
CREATE INDEX idx_has_extended_chords ON public.musical_metadata USING btree (has_extended_chords) WHERE (has_extended_chords = true);
CREATE INDEX idx_has_seventh_chords ON public.musical_metadata USING btree (has_seventh_chords) WHERE (has_seventh_chords = true);
CREATE INDEX idx_metadata_bpm ON public.musical_metadata USING btree (bpm) WHERE (bpm IS NOT NULL);
CREATE INDEX idx_metadata_characteristics ON public.musical_metadata USING btree (is_percussive, is_monophonic, has_chords);
CREATE INDEX idx_metadata_density ON public.musical_metadata USING btree (note_density DESC);
CREATE INDEX idx_metadata_has_melody ON public.musical_metadata USING btree (has_melody) WHERE (has_melody = true);
CREATE INDEX idx_metadata_key ON public.musical_metadata USING btree (key_signature) WHERE (key_signature <> 'UNKNOWN'::public.musical_key);
CREATE INDEX idx_metadata_notes ON public.musical_metadata USING btree (total_notes DESC);
CREATE INDEX idx_metadata_pitch_range ON public.musical_metadata USING btree (pitch_range_min, pitch_range_max);
CREATE INDEX idx_metadata_polyphony ON public.musical_metadata USING btree (polyphony_max) WHERE (polyphony_max IS NOT NULL);
CREATE INDEX idx_metadata_time_sig ON public.musical_metadata USING btree (time_signature_numerator, time_signature_denominator);
